name: Mark Warman
favicon: null
layout_spectrum: 0.6501369380857795
typography_spectrum: 0.9313755235634744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.031575759407132864
  lightness: 0.14624588005244732
  saturation: 0.2566153921652585
  rhythmicContrast: 0.021513168467208743
purpose: []
